"""Tests for PM-facing report generation."""

from __future__ import annotations

from datetime import UTC, datetime
from unittest.mock import AsyncMock, patch

import pytest

from shoal.core.journal import append_entry
from shoal.core.state import create_session, update_session
from shoal.models.config.workspace import TeamReportTargetConfig
from shoal.models.state import SessionStatus
from shoal.services.report import (
    generate_session_report,
    generate_sprint_report,
    generate_team_report,
    post_sprint_report,
)


@pytest.mark.asyncio
async def test_generate_session_report_returns_llm_report(mock_dirs) -> None:
    """Session report uses session state, journal data, and LLM output."""
    session = await create_session("alpha", "claude", "/tmp/repo")
    append_entry(session.id, "Implemented the report feature.", source="agent")

    with (
        patch(
            "shoal.services.report._latest_dreamer_summary",
            new=AsyncMock(return_value="Dreamer saw steady progress."),
        ),
        patch(
            "shoal.services.ai_client.call_llm",
            new=AsyncMock(return_value="## Current work\nThe agent is closing out the feature."),
        ),
    ):
        report = await generate_session_report("alpha", model="test-model")

    assert "# Session Report: alpha" in report
    assert "The agent is closing out the feature." in report
    assert "Generated by shoal report" in report


@pytest.mark.asyncio
async def test_generate_session_report_raises_for_missing_session(mock_dirs) -> None:
    """Missing sessions raise a clear error."""
    with pytest.raises(RuntimeError, match="Session not found: missing"):
        await generate_session_report("missing")


@pytest.mark.asyncio
async def test_generate_team_report_fallback_filters_to_matching_team(mock_dirs) -> None:
    """Team report fallback includes only matching team sessions."""
    be_session = await create_session(
        "be-impl",
        "claude",
        "/tmp/repo",
        tags=["linear:BE-123"],
    )
    fe_session = await create_session(
        "fe-impl",
        "claude",
        "/tmp/repo",
        tags=["linear:FE-123"],
    )
    append_entry(be_session.id, "Backend work in progress.", source="agent")
    append_entry(fe_session.id, "Frontend work in progress.", source="agent")
    await update_session(be_session.id, status=SessionStatus.running)
    await update_session(fe_session.id, status=SessionStatus.running)

    with (
        patch("shoal.services.report._linear_context", new=AsyncMock(return_value="Cycle: BE")),
        patch(
            "shoal.services.ai_client.call_llm",
            new=AsyncMock(side_effect=RuntimeError("LLM unavailable")),
        ),
    ):
        report = await generate_team_report(
            "Backend",
            "be",
            linear_team_key="BE",
            model="test-model",
        )

    assert "# Backend Team Status" in report
    assert "be-impl" in report
    assert "fe-impl" not in report


@pytest.mark.asyncio
async def test_generate_sprint_report_fallback_groups_sessions(mock_dirs) -> None:
    """Sprint fallback groups completed, in-progress, and blocked sessions."""
    completed = await create_session(
        "be-done",
        "claude",
        "/tmp/repo",
        tags=["linear:BE-1"],
    )
    running = await create_session(
        "be-run",
        "claude",
        "/tmp/repo",
        tags=["linear:BE-2"],
    )
    blocked = await create_session(
        "be-blocked",
        "claude",
        "/tmp/repo",
        tags=["linear:BE-3"],
    )
    append_entry(completed.id, "Finished implementation.", source="agent")
    append_entry(running.id, "Still working on tests.", source="agent")
    append_entry(blocked.id, "Hit a dependency issue.", source="agent")

    await update_session(completed.id, completed_at=datetime.now(UTC))
    await update_session(running.id, status=SessionStatus.running)
    await update_session(blocked.id, status=SessionStatus.error)

    with (
        patch(
            "shoal.services.report._linear_context",
            new=AsyncMock(return_value="Cycle: BE current\n- Total issues: 3"),
        ),
        patch(
            "shoal.services.ai_client.call_llm",
            new=AsyncMock(side_effect=RuntimeError("LLM unavailable")),
        ),
    ):
        report = await generate_sprint_report(
            "Backend",
            "be",
            linear_team_key="BE",
            model="test-model",
        )

    assert "# Cycle: BE current — Sprint Summary" in report
    assert "be-done" in report
    assert "be-run" in report
    assert "be-blocked" in report


@pytest.mark.asyncio
async def test_post_sprint_report_publishes_to_linear(mock_dirs) -> None:
    """Posting a sprint report resolves the target and creates a Linear update."""
    completed = await create_session(
        "be-release",
        "claude",
        "/tmp/repo",
        tags=["linear:BE-8"],
    )
    append_entry(completed.id, "Finished release hardening.", source="agent")
    await update_session(completed.id, completed_at=datetime.now(UTC))

    fake_bridge = AsyncMock()
    fake_bridge.resolve_target.return_value = type(
        "Target",
        (),
        {
            "kind": "project",
            "id": "proj-1",
            "name": "Backend Platform",
            "slug": "backend-platform",
            "url": "https://linear.app/project/backend-platform",
        },
    )()
    fake_bridge.create_status_update.return_value = type(
        "Update",
        (),
        {
            "kind": "project",
            "id": "upd-1",
            "url": "https://linear.app/update/upd-1",
            "health": "onTrack",
        },
    )()

    with (
        patch(
            "shoal.services.report._linear_context",
            new=AsyncMock(return_value="Cycle: BE current\n- Total issues: 1"),
        ),
        patch(
            "shoal.services.ai_client.call_llm",
            new=AsyncMock(return_value="## Completed\nShipped the sprint scope."),
        ),
        patch("shoal.services.linear_bridge.get_linear_bridge", return_value=fake_bridge),
    ):
        result = await post_sprint_report(
            "Backend",
            "be",
            report_target=TeamReportTargetConfig(type="project", slug="backend-platform"),
            linear_team_key="BE",
            model="test-model",
        )

    assert "Sprint Summary" in result.report
    assert result.target_kind == "project"
    assert result.target_name == "Backend Platform"
    assert result.update_url == "https://linear.app/update/upd-1"
    assert result.health == "onTrack"
    fake_bridge.resolve_target.assert_awaited_once_with(
        kind="project",
        id="",
        slug="backend-platform",
        name="",
    )
    fake_bridge.create_status_update.assert_awaited_once()
    fake_bridge.close.assert_awaited_once()
