# Shoal fish shell integration bootstrap
# Loaded automatically when fish starts
# Generated by: shoal setup fish

# Only load in interactive sessions
status is-interactive; or return

# Set environment variable to indicate fish shell
set -gx SHOAL_SHELL fish

# Abbreviations for common commands
abbr -a sa shoal attach
abbr -a sl shoal ls
abbr -a ss shoal status
abbr -a sp shoal popup
abbr -a sn shoal new
abbr -a sk shoal kill
abbr -a si shoal info

# Key bindings
function __shoal_bind_keys
    # Ctrl+S - Launch shoal popup dashboard
    bind \cs 'shoal popup; commandline -f repaint'

    # Alt+A - Quick attach (using fzf if available)
    if type -q fzf
        bind \ea 'shoal-quick-attach; commandline -f repaint'
    end
end

# Apply key bindings
__shoal_bind_keys

# Event handler for fish_preexec - detect shoal sessions
function __shoal_preexec --on-event fish_preexec
    # Detect if running inside a shoal tmux session
    if set -q TMUX
        set -l tmux_session (tmux display-message -p '#S' 2>/dev/null)
        if test -n "$tmux_session"
            # Store current shoal session in universal variable for cross-session access
            set -g __shoal_last_session $tmux_session
        end
    end
end

# Optional: Add shoal status to fish prompt
# Uncomment the following to show current shoal session in prompt:
#
# function fish_right_prompt
#     if set -q TMUX
#         set -l session (tmux display-message -p '#S' 2>/dev/null)
#         if test -n "$session"
#             echo -n (set_color cyan)"[$session]"(set_color normal)
#         end
#     end
# end
