# Fish shell completions for Shoal
# Generated by: shoal setup fish

# Disable file completions by default
complete -c shoal -f

# Helper function to get session names dynamically
function __shoal_sessions
    shoal ls --format plain 2>/dev/null
end

# Helper function to get MCP server names
function __shoal_mcp_servers
    shoal mcp ls --format plain 2>/dev/null
end

# Helper function to get robo profile names
function __shoal_robo_profiles
    shoal robo profiles --format plain 2>/dev/null
end

# Top-level commands
complete -c shoal -n "__fish_use_subcommand" -a "new" -d "Create new session"
complete -c shoal -n "__fish_use_subcommand" -a "ls" -d "List sessions"
complete -c shoal -n "__fish_use_subcommand" -a "info" -d "Show session details"
complete -c shoal -n "__fish_use_subcommand" -a "rename" -d "Rename session"
complete -c shoal -n "__fish_use_subcommand" -a "logs" -d "Show session logs"
complete -c shoal -n "__fish_use_subcommand" -a "attach" -d "Attach to session"
complete -c shoal -n "__fish_use_subcommand" -a "detach" -d "Detach from session"
complete -c shoal -n "__fish_use_subcommand" -a "fork" -d "Fork existing session"
complete -c shoal -n "__fish_use_subcommand" -a "kill" -d "Kill session"
complete -c shoal -n "__fish_use_subcommand" -a "prune" -d "Remove stopped sessions"
complete -c shoal -n "__fish_use_subcommand" -a "status" -d "Show status overview"
complete -c shoal -n "__fish_use_subcommand" -a "popup" -d "Interactive dashboard"
complete -c shoal -n "__fish_use_subcommand" -a "init" -d "Initialize Shoal"
complete -c shoal -n "__fish_use_subcommand" -a "check" -d "Check dependencies"
complete -c shoal -n "__fish_use_subcommand" -a "version" -d "Print version"
complete -c shoal -n "__fish_use_subcommand" -a "serve" -d "Start API server"

# Sub-groups
complete -c shoal -n "__fish_use_subcommand" -a "template" -d "Template management"
complete -c shoal -n "__fish_use_subcommand" -a "wt" -d "Worktree management"
complete -c shoal -n "__fish_use_subcommand" -a "worktree" -d "Worktree management"
complete -c shoal -n "__fish_use_subcommand" -a "mcp" -d "MCP server pool"
complete -c shoal -n "__fish_use_subcommand" -a "robo" -d "Robo (supervisory agent)"
complete -c shoal -n "__fish_use_subcommand" -a "nvim" -d "Neovim integration"
complete -c shoal -n "__fish_use_subcommand" -a "watcher" -d "Background status watcher"
complete -c shoal -n "__fish_use_subcommand" -a "demo" -d "Demo environment"
complete -c shoal -n "__fish_use_subcommand" -a "setup" -d "Setup shell integrations"

# Dynamic session name completions for commands that need them
complete -c shoal -n "__fish_seen_subcommand_from attach" -a "(__shoal_sessions)" -d "Session"
complete -c shoal -n "__fish_seen_subcommand_from info" -a "(__shoal_sessions)" -d "Session"
complete -c shoal -n "__fish_seen_subcommand_from kill" -a "(__shoal_sessions)" -d "Session"
complete -c shoal -n "__fish_seen_subcommand_from logs" -a "(__shoal_sessions)" -d "Session"
complete -c shoal -n "__fish_seen_subcommand_from rename" -a "(__shoal_sessions)" -d "Session"
complete -c shoal -n "__fish_seen_subcommand_from fork" -a "(__shoal_sessions)" -d "Session"

# Helper function to get available tool names
function __shoal_tools
    test -d ~/.config/shoal/tools; or return
    for f in ~/.config/shoal/tools/*.toml
        string replace -r '.*/(.*)\.toml$' '$1' -- $f
    end
end

# Helper function to get available template names
function __shoal_templates
    test -d ~/.config/shoal/templates; or return
    for f in ~/.config/shoal/templates/*.toml
        string replace -r '.*/(.*)\.toml$' '$1' -- $f
    end
end

# Common flags for session creation
complete -c shoal -n "__fish_seen_subcommand_from new fork" -l "worktree" -s "w" -d "Create in worktree"
complete -c shoal -n "__fish_seen_subcommand_from new fork" -l "branch" -s "b" -d "Create branch"
complete -c shoal -n "__fish_seen_subcommand_from new fork" -l "robo" -s "r" -d "Start with robo" -xa "(__shoal_robo_profiles)"
complete -c shoal -n "__fish_seen_subcommand_from new" -l "tool" -s "t" -d "AI tool to use" -xa "(__shoal_tools)"
complete -c shoal -n "__fish_seen_subcommand_from new" -l "template" -d "Session template" -xa "(__shoal_templates)"
complete -c shoal -n "__fish_seen_subcommand_from new" -l "dry-run" -d "Preview without creating"

# MCP subcommands
complete -c shoal -n "__fish_seen_subcommand_from mcp; and not __fish_seen_subcommand_from ls start attach kill status" -a "ls" -d "List MCP servers"
complete -c shoal -n "__fish_seen_subcommand_from mcp; and not __fish_seen_subcommand_from ls start attach kill status" -a "start" -d "Start MCP server"
complete -c shoal -n "__fish_seen_subcommand_from mcp; and not __fish_seen_subcommand_from ls start attach kill status" -a "attach" -d "Attach server to session"
complete -c shoal -n "__fish_seen_subcommand_from mcp; and not __fish_seen_subcommand_from ls start attach kill status" -a "kill" -d "Kill MCP server"
complete -c shoal -n "__fish_seen_subcommand_from mcp; and not __fish_seen_subcommand_from ls start attach kill status" -a "status" -d "MCP pool status"

# MCP server name completions for commands that take a server argument
complete -c shoal -n "__fish_seen_subcommand_from mcp; and __fish_seen_subcommand_from start" -a "(__shoal_mcp_servers)" -d "MCP server"
complete -c shoal -n "__fish_seen_subcommand_from mcp; and __fish_seen_subcommand_from attach" -a "(__shoal_mcp_servers)" -d "MCP server"
complete -c shoal -n "__fish_seen_subcommand_from mcp; and __fish_seen_subcommand_from kill" -a "(__shoal_mcp_servers)" -d "MCP server"

# Robo subcommands
complete -c shoal -n "__fish_seen_subcommand_from robo; and not __fish_seen_subcommand_from send approve status profiles" -a "send" -d "Send keys to robo"
complete -c shoal -n "__fish_seen_subcommand_from robo; and not __fish_seen_subcommand_from send approve status profiles" -a "approve" -d "Approve robo action"
complete -c shoal -n "__fish_seen_subcommand_from robo; and not __fish_seen_subcommand_from send approve status profiles" -a "status" -d "Robo status"
complete -c shoal -n "__fish_seen_subcommand_from robo; and not __fish_seen_subcommand_from send approve status profiles" -a "profiles" -d "List robo profiles"

# Worktree subcommands
complete -c shoal -n "__fish_seen_subcommand_from wt; and not __fish_seen_subcommand_from finish prune" -a "finish" -d "Finish worktree session"
complete -c shoal -n "__fish_seen_subcommand_from wt; and not __fish_seen_subcommand_from finish prune" -a "prune" -d "Clean up worktrees"
complete -c shoal -n "__fish_seen_subcommand_from worktree; and not __fish_seen_subcommand_from finish prune" -a "finish" -d "Finish worktree session"
complete -c shoal -n "__fish_seen_subcommand_from worktree; and not __fish_seen_subcommand_from finish prune" -a "prune" -d "Clean up worktrees"

# Watcher subcommands
complete -c shoal -n "__fish_seen_subcommand_from watcher; and not __fish_seen_subcommand_from start stop status" -a "start" -d "Start watcher"
complete -c shoal -n "__fish_seen_subcommand_from watcher; and not __fish_seen_subcommand_from start stop status" -a "stop" -d "Stop watcher"
complete -c shoal -n "__fish_seen_subcommand_from watcher; and not __fish_seen_subcommand_from start stop status" -a "status" -d "Watcher status"

# Demo subcommands
complete -c shoal -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from start stop" -a "start" -d "Start demo environment"
complete -c shoal -n "__fish_seen_subcommand_from demo; and not __fish_seen_subcommand_from start stop" -a "stop" -d "Stop demo environment"

# Setup subcommands
complete -c shoal -n "__fish_seen_subcommand_from setup; and not __fish_seen_subcommand_from fish" -a "fish" -d "Install fish shell integration"

# Template subcommands
complete -c shoal -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from ls show validate mixins" -a "ls" -d "List templates"
complete -c shoal -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from ls show validate mixins" -a "show" -d "Show template details"
complete -c shoal -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from ls show validate mixins" -a "validate" -d "Validate templates"
complete -c shoal -n "__fish_seen_subcommand_from template; and not __fish_seen_subcommand_from ls show validate mixins" -a "mixins" -d "List template mixins"
complete -c shoal -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from show" -a "(__shoal_templates)" -d "Template"
complete -c shoal -n "__fish_seen_subcommand_from template; and __fish_seen_subcommand_from validate" -a "(__shoal_templates)" -d "Template"

# Nvim subcommands
complete -c shoal -n "__fish_seen_subcommand_from nvim; and not __fish_seen_subcommand_from send diagnostics" -a "send" -d "Send command to nvim"
complete -c shoal -n "__fish_seen_subcommand_from nvim; and not __fish_seen_subcommand_from send diagnostics" -a "diagnostics" -d "Get nvim diagnostics"
