# Shoal lifecycle event hooks for fish shell
# Loaded automatically when fish starts
# Generated by: shoal setup fish
#
# These hooks respond to events emitted by Shoal's lifecycle system.
# The Python side emits: fish -c 'emit shoal_status_changed <name> <status>'
# Additional events: shoal_session_created, shoal_session_killed
#
# Uncomment and customize the handlers below to react to session events.
# Examples: desktop notifications, sound alerts, tmux status refresh, logging.

# Only load in interactive sessions
status is-interactive; or return


# --- Dispatcher: routes shoal_status_changed to per-status handlers ---

function __shoal_on_status_changed --on-event shoal_status_changed \
    --description "Dispatch shoal status changes to per-status handlers"
    set -l name $argv[1]
    set -l new_status $argv[2]

    switch $new_status
        case waiting
            __shoal_on_waiting $name
        case error
            __shoal_on_error $name
        case running
            __shoal_on_running $name
        case idle
            __shoal_on_idle $name
        case stopped
            __shoal_on_stopped $name
    end
end


# --- Per-status handlers (customize these) ---

# Called when a session enters "waiting" status (agent needs input/approval)
function __shoal_on_waiting --description "Handle session waiting for input"
    set -l name $argv[1]
    # Uncomment to enable desktop notification:
    # notify-send "Shoal: $name" "Waiting for input" 2>/dev/null
    # Uncomment to enable ntfy webhook:
    # curl -s -d "Session $name is waiting for input" ntfy.sh/your-topic &>/dev/null &
end

# Called when a session enters "error" status
function __shoal_on_error --description "Handle session error"
    set -l name $argv[1]
    # Uncomment to enable desktop notification:
    # notify-send --urgency=critical "Shoal: $name" "Error detected" 2>/dev/null
end

# Called when a session enters "running" status
function __shoal_on_running --description "Handle session running"
    set -l name $argv[1]
    # Usually no notification needed for running status
end

# Called when a session enters "idle" status
function __shoal_on_idle --description "Handle session idle"
    set -l name $argv[1]
    # Uncomment to enable desktop notification:
    # notify-send "Shoal: $name" "Agent is idle" 2>/dev/null
end

# Called when a session enters "stopped" status
function __shoal_on_stopped --description "Handle session stopped"
    set -l name $argv[1]
    # Uncomment to enable desktop notification:
    # notify-send "Shoal: $name" "Session stopped" 2>/dev/null
end


# --- Session lifecycle events ---

function __shoal_on_created --on-event shoal_session_created \
    --description "Handle new session creation"
    set -l name $argv[1]
    # Uncomment to enable desktop notification:
    # notify-send "Shoal: $name" "Session created" 2>/dev/null
end

function __shoal_on_killed --on-event shoal_session_killed \
    --description "Handle session termination"
    set -l name $argv[1]
    # Uncomment to enable desktop notification:
    # notify-send "Shoal: $name" "Session killed" 2>/dev/null
end
