# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import a2a_claw_pb2 as a2a__claw__pb2
import a2a_core_pb2 as a2a__core__pb2
import grpc

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in a2a_claw_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AgentLoopStub:
    """=============================================================================
    AgentLoop Service
    =============================================================================

    AgentLoop
    ---------
    Primary gRPC service exposed by each Claw runtime.

    The Clawplexer acts as client; Claw runtime acts as server.
    This allows Claws to run without egress network access (common in K8s).


    Auth: All RPCs expect `authorization: Bearer <jwt>` metadata.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/SendMessage",
            request_serializer=a2a__core__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=a2a__core__pb2.SendMessageResponse.FromString,
            _registered_method=True,
        )
        self.SendStreamingMessage = channel.unary_stream(
            "/lobster.party.v1.a2a.AgentLoop/SendStreamingMessage",
            request_serializer=a2a__core__pb2.SendStreamingMessageRequest.SerializeToString,
            response_deserializer=a2a__core__pb2.Message.FromString,
            _registered_method=True,
        )
        self.GetTask = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/GetTask",
            request_serializer=a2a__core__pb2.GetTaskRequest.SerializeToString,
            response_deserializer=a2a__core__pb2.Task.FromString,
            _registered_method=True,
        )
        self.ListTasks = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/ListTasks",
            request_serializer=a2a__core__pb2.ListTasksRequest.SerializeToString,
            response_deserializer=a2a__core__pb2.ListTasksResponse.FromString,
            _registered_method=True,
        )
        self.CancelTask = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/CancelTask",
            request_serializer=a2a__core__pb2.CancelTaskRequest.SerializeToString,
            response_deserializer=a2a__core__pb2.CancelTaskResponse.FromString,
            _registered_method=True,
        )
        self.SubscribeToTask = channel.unary_stream(
            "/lobster.party.v1.a2a.AgentLoop/SubscribeToTask",
            request_serializer=a2a__core__pb2.SubscribeToTaskRequest.SerializeToString,
            response_deserializer=a2a__claw__pb2.TaskEvent.FromString,
            _registered_method=True,
        )
        self.GetAgentCard = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/GetAgentCard",
            request_serializer=a2a__core__pb2.GetAgentCardRequest.SerializeToString,
            response_deserializer=a2a__core__pb2.AgentCard.FromString,
            _registered_method=True,
        )
        self.GetExtendedAgentCard = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/GetExtendedAgentCard",
            request_serializer=a2a__core__pb2.GetExtendedAgentCardRequest.SerializeToString,
            response_deserializer=a2a__claw__pb2.ExtendedAgentCard.FromString,
            _registered_method=True,
        )
        self.AgentToAgent = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/AgentToAgent",
            request_serializer=a2a__claw__pb2.AgentToAgentRequest.SerializeToString,
            response_deserializer=a2a__claw__pb2.AgentToAgentResponse.FromString,
            _registered_method=True,
        )
        self.Turn = channel.unary_stream(
            "/lobster.party.v1.a2a.AgentLoop/Turn",
            request_serializer=a2a__claw__pb2.TurnRequest.SerializeToString,
            response_deserializer=a2a__claw__pb2.TurnStreamItem.FromString,
            _registered_method=True,
        )
        self.Status = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/Status",
            request_serializer=a2a__claw__pb2.StatusRequest.SerializeToString,
            response_deserializer=a2a__claw__pb2.StatusResponse.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/lobster.party.v1.a2a.AgentLoop/Health",
            request_serializer=a2a__claw__pb2.HealthRequest.SerializeToString,
            response_deserializer=a2a__claw__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.Subscribe = channel.unary_stream(
            "/lobster.party.v1.a2a.AgentLoop/Subscribe",
            request_serializer=a2a__claw__pb2.SubscribeRequest.SerializeToString,
            response_deserializer=a2a__claw__pb2.Event.FromString,
            _registered_method=True,
        )


class AgentLoopServicer:
    """=============================================================================
    AgentLoop Service
    =============================================================================

    AgentLoop
    ---------
    Primary gRPC service exposed by each Claw runtime.

    The Clawplexer acts as client; Claw runtime acts as server.
    This allows Claws to run without egress network access (common in K8s).


    Auth: All RPCs expect `authorization: Bearer <jwt>` metadata.

    """

    def SendMessage(self, request, context):
        """=== A2A Core Operations ===

        SendMessage
        -----------
        Submit a Message to the Claw for processing.

        This is the primary A2A operation for sending work to a Claw.
        It replaces the legacy Turn RPC.

        Request: SendMessageRequest
        - task_id: Optional task ID for idempotency (generated if not provided)
        - message: The Message to process
        - config: Optional configuration

        Response: SendMessageResponse
        - Either a Task (for async processing) or direct Message (for sync)

        A2A spec: https://a2a-protocol.org/latest/specification/#send-message

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendStreamingMessage(self, request, context):
        """SendStreamingMessage
        -------------------
        Submit a Message with real-time streaming of updates.

        The stream returns Messages as they are generated, allowing
        progressive output without waiting for completion.

        A2A spec: https://a2a-protocol.org/latest/specification/#send-streaming-message

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTask(self, request, context):
        """GetTask
        -------
        Retrieve current state of a Task.

        A2A spec: https://a2a-protocol.org/latest/specification/#get-task

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTasks(self, request, context):
        """ListTasks
        ---------
        List Tasks with optional filtering by context or status.

        A2A spec: https://a2a-protocol.org/latest/specification/#list-tasks

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelTask(self, request, context):
        """CancelTask
        ----------
        Cancel a running Task.

        A2A spec: https://a2a-protocol.org/latest/specification/#cancel-task

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubscribeToTask(self, request, context):
        """SubscribeToTask
        ---------------
        Subscribe to real-time Task status and artifact updates.

        Auth metadata expects: `authorization: Bearer <jwt>`

        The stream emits TaskEvent envelopes which can contain either:
        - TaskStatusUpdateEvent: task state transitions (working, completed, etc.)
        - TaskArtifactUpdateEvent: artifact chunks as they are produced

        A2A spec: https://a2a-protocol.org/latest/specification/#subscribe-to-task

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAgentCard(self, request, context):
        """GetAgentCard
        ------------
        Get this Claw's AgentCard for agent discovery.

        Every Claw exposes its own AgentCard describing its capabilities.
        This is the primary A2A agent discovery mechanism.

        A2A spec: https://a2a-protocol.org/latest/specification/#agent-discovery

        TODO(be-8l8l7t-3-a2a): Also expose via .well-known/agent.json HTTP endpoint

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetExtendedAgentCard(self, request, context):
        """GetExtendedAgentCard
        -------------------
        Get AgentCard with authentication requirements.

        Used when the agent requires authentication to access certain capabilities.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AgentToAgent(self, request, context):
        """=== AgentToAgent (InterClaw) ===

        AgentToAgent is the A2A term for communication between agents.
        Internal lobster-party name: "InterClaw"

        Communication flow:
        Source Claw --> Clawplexer (ACL check) --> Target Claw
        Source Claw <-- Clawplexer (relay) <-- Target Claw

        TODO(be-8l8l7t-3-a2a): Consider renaming InterClawRequest to AgentToAgentRequest
        in future major version for A2A alignment. 'InterClaw' remains canonical internally.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Turn(self, request, context):
        """=== Legacy lobster-loop Operations ===

        These RPCs are kept for backward compatibility.
        New code should use the A2A-aligned equivalents above.

        Legacy mapping:
        Turn        -> SendMessage
        Subscribe   -> SubscribeToTask / SendStreamingMessage
        InterClaw   -> AgentToAgent (same semantics, new name)


        Turn
        -----
        Submit a unit of work to the Claw (legacy, use SendMessage instead).

        Returns a stream of TurnStreamItem - typing indicators while processing,
        followed by the final TurnResponse.

        TODO(be-8l8l7t-3-a2a): Deprecate in favor of SendMessage

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Status(self, request, context):
        """Status
        ------
        Query current state and resource usage of a Claw.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Health
        ------
        Lightweight liveness check for the Claw runtime process.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Subscribe(self, request, context):
        """Subscribe
        ---------
        Subscribe to a stream of events from the Claw (legacy).

        Prefer SubscribeToTask for A2A-aligned task subscriptions.
        Use this for lower-level Claw lifecycle events.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AgentLoopServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendMessage": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=a2a__core__pb2.SendMessageRequest.FromString,
            response_serializer=a2a__core__pb2.SendMessageResponse.SerializeToString,
        ),
        "SendStreamingMessage": grpc.unary_stream_rpc_method_handler(
            servicer.SendStreamingMessage,
            request_deserializer=a2a__core__pb2.SendStreamingMessageRequest.FromString,
            response_serializer=a2a__core__pb2.Message.SerializeToString,
        ),
        "GetTask": grpc.unary_unary_rpc_method_handler(
            servicer.GetTask,
            request_deserializer=a2a__core__pb2.GetTaskRequest.FromString,
            response_serializer=a2a__core__pb2.Task.SerializeToString,
        ),
        "ListTasks": grpc.unary_unary_rpc_method_handler(
            servicer.ListTasks,
            request_deserializer=a2a__core__pb2.ListTasksRequest.FromString,
            response_serializer=a2a__core__pb2.ListTasksResponse.SerializeToString,
        ),
        "CancelTask": grpc.unary_unary_rpc_method_handler(
            servicer.CancelTask,
            request_deserializer=a2a__core__pb2.CancelTaskRequest.FromString,
            response_serializer=a2a__core__pb2.CancelTaskResponse.SerializeToString,
        ),
        "SubscribeToTask": grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeToTask,
            request_deserializer=a2a__core__pb2.SubscribeToTaskRequest.FromString,
            response_serializer=a2a__claw__pb2.TaskEvent.SerializeToString,
        ),
        "GetAgentCard": grpc.unary_unary_rpc_method_handler(
            servicer.GetAgentCard,
            request_deserializer=a2a__core__pb2.GetAgentCardRequest.FromString,
            response_serializer=a2a__core__pb2.AgentCard.SerializeToString,
        ),
        "GetExtendedAgentCard": grpc.unary_unary_rpc_method_handler(
            servicer.GetExtendedAgentCard,
            request_deserializer=a2a__core__pb2.GetExtendedAgentCardRequest.FromString,
            response_serializer=a2a__claw__pb2.ExtendedAgentCard.SerializeToString,
        ),
        "AgentToAgent": grpc.unary_unary_rpc_method_handler(
            servicer.AgentToAgent,
            request_deserializer=a2a__claw__pb2.AgentToAgentRequest.FromString,
            response_serializer=a2a__claw__pb2.AgentToAgentResponse.SerializeToString,
        ),
        "Turn": grpc.unary_stream_rpc_method_handler(
            servicer.Turn,
            request_deserializer=a2a__claw__pb2.TurnRequest.FromString,
            response_serializer=a2a__claw__pb2.TurnStreamItem.SerializeToString,
        ),
        "Status": grpc.unary_unary_rpc_method_handler(
            servicer.Status,
            request_deserializer=a2a__claw__pb2.StatusRequest.FromString,
            response_serializer=a2a__claw__pb2.StatusResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=a2a__claw__pb2.HealthRequest.FromString,
            response_serializer=a2a__claw__pb2.HealthResponse.SerializeToString,
        ),
        "Subscribe": grpc.unary_stream_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=a2a__claw__pb2.SubscribeRequest.FromString,
            response_serializer=a2a__claw__pb2.Event.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "lobster.party.v1.a2a.AgentLoop", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("lobster.party.v1.a2a.AgentLoop", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AgentLoop:
    """=============================================================================
    AgentLoop Service
    =============================================================================

    AgentLoop
    ---------
    Primary gRPC service exposed by each Claw runtime.

    The Clawplexer acts as client; Claw runtime acts as server.
    This allows Claws to run without egress network access (common in K8s).


    Auth: All RPCs expect `authorization: Bearer <jwt>` metadata.

    """

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/SendMessage",
            a2a__core__pb2.SendMessageRequest.SerializeToString,
            a2a__core__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendStreamingMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/SendStreamingMessage",
            a2a__core__pb2.SendStreamingMessageRequest.SerializeToString,
            a2a__core__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/GetTask",
            a2a__core__pb2.GetTaskRequest.SerializeToString,
            a2a__core__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTasks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/ListTasks",
            a2a__core__pb2.ListTasksRequest.SerializeToString,
            a2a__core__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/CancelTask",
            a2a__core__pb2.CancelTaskRequest.SerializeToString,
            a2a__core__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubscribeToTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/SubscribeToTask",
            a2a__core__pb2.SubscribeToTaskRequest.SerializeToString,
            a2a__claw__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAgentCard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/GetAgentCard",
            a2a__core__pb2.GetAgentCardRequest.SerializeToString,
            a2a__core__pb2.AgentCard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetExtendedAgentCard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/GetExtendedAgentCard",
            a2a__core__pb2.GetExtendedAgentCardRequest.SerializeToString,
            a2a__claw__pb2.ExtendedAgentCard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AgentToAgent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/AgentToAgent",
            a2a__claw__pb2.AgentToAgentRequest.SerializeToString,
            a2a__claw__pb2.AgentToAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Turn(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/Turn",
            a2a__claw__pb2.TurnRequest.SerializeToString,
            a2a__claw__pb2.TurnStreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Status(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/Status",
            a2a__claw__pb2.StatusRequest.SerializeToString,
            a2a__claw__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/Health",
            a2a__claw__pb2.HealthRequest.SerializeToString,
            a2a__claw__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Subscribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/lobster.party.v1.a2a.AgentLoop/Subscribe",
            a2a__claw__pb2.SubscribeRequest.SerializeToString,
            a2a__claw__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
