syntax = "proto3";
package lobster.party.delegation.v1;

import "google/protobuf/wrappers.proto";
import "google/protobuf/duration.proto";

service DelegationService {
  rpc Execute(stream ExecuteRequest) returns (stream ExecuteEvent);
}

message ExecuteRequest {
  oneof msg {
    Start start = 1;
    google.protobuf.BytesValue stdin = 2;
    EofReached stdin_eof = 3;
    Cancel cancel = 4;
  }
}

message Start {
  string request_id = 1;
  string command_id = 2;
  repeated string args = 3;
  map<string, string> env = 4;
  string cwd = 5;
  google.protobuf.Duration timeout = 6;
}

message EofReached {}

message Cancel { string reason = 1; }

message ExecuteEvent {
  oneof msg {
    Started started = 1;
    google.protobuf.BytesValue stdout = 2;
    google.protobuf.BytesValue stderr = 3;
    EofReached stdout_eof = 4;
    EofReached stderr_eof = 5;
    Exited exited = 6;
    ProtocolError error = 7;
  }
}

message Started { uint32 pid = 1; }

message Exited {
  int32 exit_code = 1;
  int32 signal = 2;
  bool timed_out = 3;
  google.protobuf.Duration runtime = 4;
}

message ProtocolError {
  string code = 1;
  string message = 2;
}