# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from shoal.core.proto import lobster_loop_pb2 as lobster__loop__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in lobster_loop_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class LobsterLoopStub:
    """=============================================================================
    Service Definition: LobsterLoop
    =============================================================================

    LobsterLoop is the primary gRPC service exposed by each Claw runtime.
    The Clawplexer uses this service to:

    1. Submit work turns (Turn RPC)
    2. Query Claw status (Status RPC)
    3. Check Claw health (Health RPC)
    4. Subscribe to state change events (Subscribe RPC - server streaming)
    5. Send InterClaw requests to other Claws (InterClaw RPC)

    Communication Pattern
    --------------------

    The Clawplexer is the client; the Claw runtime is the server.
    This allows Claws to run without egress network access (common in K8s).

    Claw Runtime Pod Network
    ------------------------

    Claw Pods are addressed via their ClusterIP Service:

    claw-<claw_id>.lobster-party-runtime.svc:50051

    The Clawplexer maintains an endpoint cache (from K8s EndpointSlices) and
    routes gRPC calls to ready Pod endpoints only.

    Error Handling Convention
    -------------------------

    All RPCs return gRPC status codes:
    - OK (0):              Success
    - INVALID_ARGUMENT:     Malformed request (e.g., bad event_id)
    - NOT_FOUND:           Claw does not exist or is not routable
    - FAILED_PRECONDITION: Claw is not in a state that accepts work (e.g., paused)
    - UNAVAILABLE:         Claw is temporarily unreachable or overloaded
    - INTERNAL:            Unexpected error in Claw runtime
    - PERMISSION_DENIED:   InterClaw request denied by ACL
    - RESOURCE_EXHAUSTED:  InterClaw request pending permission

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Turn = channel.unary_stream(
            "/lobster.party.v1.LobsterLoop/Turn",
            request_serializer=lobster__loop__pb2.TurnRequest.SerializeToString,
            response_deserializer=lobster__loop__pb2.TurnStreamItem.FromString,
            _registered_method=True,
        )
        self.Status = channel.unary_unary(
            "/lobster.party.v1.LobsterLoop/Status",
            request_serializer=lobster__loop__pb2.StatusRequest.SerializeToString,
            response_deserializer=lobster__loop__pb2.StatusResponse.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/lobster.party.v1.LobsterLoop/Health",
            request_serializer=lobster__loop__pb2.HealthRequest.SerializeToString,
            response_deserializer=lobster__loop__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.Subscribe = channel.unary_stream(
            "/lobster.party.v1.LobsterLoop/Subscribe",
            request_serializer=lobster__loop__pb2.SubscribeRequest.SerializeToString,
            response_deserializer=lobster__loop__pb2.Event.FromString,
            _registered_method=True,
        )
        self.InterClaw = channel.unary_unary(
            "/lobster.party.v1.LobsterLoop/InterClaw",
            request_serializer=lobster__loop__pb2.InterClawRequest.SerializeToString,
            response_deserializer=lobster__loop__pb2.InterClawResponse.FromString,
            _registered_method=True,
        )


class LobsterLoopServicer:
    """=============================================================================
    Service Definition: LobsterLoop
    =============================================================================

    LobsterLoop is the primary gRPC service exposed by each Claw runtime.
    The Clawplexer uses this service to:

    1. Submit work turns (Turn RPC)
    2. Query Claw status (Status RPC)
    3. Check Claw health (Health RPC)
    4. Subscribe to state change events (Subscribe RPC - server streaming)
    5. Send InterClaw requests to other Claws (InterClaw RPC)

    Communication Pattern
    --------------------

    The Clawplexer is the client; the Claw runtime is the server.
    This allows Claws to run without egress network access (common in K8s).

    Claw Runtime Pod Network
    ------------------------

    Claw Pods are addressed via their ClusterIP Service:

    claw-<claw_id>.lobster-party-runtime.svc:50051

    The Clawplexer maintains an endpoint cache (from K8s EndpointSlices) and
    routes gRPC calls to ready Pod endpoints only.

    Error Handling Convention
    -------------------------

    All RPCs return gRPC status codes:
    - OK (0):              Success
    - INVALID_ARGUMENT:     Malformed request (e.g., bad event_id)
    - NOT_FOUND:           Claw does not exist or is not routable
    - FAILED_PRECONDITION: Claw is not in a state that accepts work (e.g., paused)
    - UNAVAILABLE:         Claw is temporarily unreachable or overloaded
    - INTERNAL:            Unexpected error in Claw runtime
    - PERMISSION_DENIED:   InterClaw request denied by ACL
    - RESOURCE_EXHAUSTED:  InterClaw request pending permission

    """

    def Turn(self, request, context):
        """Turn
        -----
        Submit a unit of work to the Claw for processing.

        The request includes:
        - claw_id:    Target Claw identifier (must match runtime's configured ID)
        - employee_id: Originating employee for auth/audit
        - payload:    Arbitrary bytes containing the turn prompt
        - event_id:   Unique identifier for idempotency
        - metadata:   Additional context (channel_id, thread_ts, etc.)

        Response is a stream of TurnStreamItem:
        - TypingEvent items are emitted while processing to show typing indicator
        - TurnResponse is emitted at the end with the final result

        Idempotency:
        The Claw MUST deduplicate turns with the same event_id within a 10-minute window.
        If a duplicate turn is detected, return the cached response without re-executing.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Status(self, request, context):
        """Status
        ------
        Query the current state and resource usage of a Claw.
        Used by the Clawplexer for routing decisions and monitoring.

        The Clawplexer SHOULD cache Status responses and refresh from the
        live RPC only when the cache is stale (>10s) or routing state is uncertain.

        Returns NOT_FOUND if the Claw does not exist.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Health
        ------
        Lightweight liveness check for the Claw runtime process.
        This is distinct from K8s liveness probes (which check the container is running).
        Health RPC checks the application-level process is healthy and ready to accept work.

        Use cases:
        - Clawplexer uses this to determine if a Claw endpoint is healthy
        - Load balancer health checks (if implemented)
        - Kubernetes readiness probes CAN call this RPC (though simpler HTTP probes are preferred)

        Returns UNKNOWN health state if the internal health check fails but process is alive.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Subscribe(self, request, context):
        """Subscribe
        ---------
        Subscribe to a stream of events from the Claw.
        This is a server-streaming RPC: the Claw pushes events to the Clawplexer.

        This enables:
        - Async state change notifications (avoid polling Status RPC)
        - Activity heartbeat events (Claw is actively processing)
        - Turn completion events (for upstream Slack acknowledgment)
        - InterClaw permission request notifications (user prompt)

        Event Types (filterable via event_types):
        - STATE_CHANGED:                  Claw transitioned to a new lifecycle state
        - HEALTH_CHANGED:                 Claw health status changed
        - ACTIVITY:                       Periodic heartbeat with active session count
        - TURN_COMPLETED:                 A submitted turn finished processing
        - INTERCLAW_PERMISSION_REQUEST:   Incoming InterClaw request needs permission
        - INTERCLAW_COMPLETED:            InterClaw request completed (success/failure)

        Stream Management:
        - The Clawplexer MAY open multiple Subscribe streams to the same Claw
        - The Claw MUST send heartbeats every 30s to keep the stream alive
        - If the stream is dropped, the Clawplexer will re-establish it

        The Claw SHOULD buffer events if the subscriber is slow, but MUST cap
        the buffer to 1000 events to prevent memory exhaustion.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InterClaw(self, request, context):
        """InterClaw
        ----------
        Send a request to another Claw via the Clawplexer relay.

        Flow:
        1. Source Claw calls InterClaw to request work from Target Claw
        2. Clawplexer checks ACL for (target_claw_id, source_claw_id)
        3. If PERMISSION_DENIED: return PERMISSION_DENIED error
        4. If no ACL entry or cache miss: return RESOURCE_EXHAUSTED (pending)
        - Clawplexer stores pending request and emits EVENT_TYPE_INTERCLAW_PERMISSION_REQUEST
        - Target user's Claw receives notification via Subscribe stream
        - User approves/denies via SetInterClawPermission RPC
        5. If PERMISSION_ALLOW: forward request to Target Claw
        6. If PERMISSION_ALWAYS_ALLOW: forward request immediately, update cache
        7. Target Claw processes request and returns response
        8. Clawplexer proxies response back to Source Claw

        For PERMISSION_ALLOW (one-time):
        - Clawplexer marks ACL entry as consumed (sets expires_at)
        - Subsequent requests from same source require re-approval

        Error codes specific to InterClaw:
        - PERMISSION_DENIED (7):   Target has explicitly denied this source
        - RESOURCE_EXHAUSTED (8): Permission pending; user must approve
        - FAILED_PRECONDITION:    Target is not in a routable state

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LobsterLoopServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Turn": grpc.unary_stream_rpc_method_handler(
            servicer.Turn,
            request_deserializer=lobster__loop__pb2.TurnRequest.FromString,
            response_serializer=lobster__loop__pb2.TurnStreamItem.SerializeToString,
        ),
        "Status": grpc.unary_unary_rpc_method_handler(
            servicer.Status,
            request_deserializer=lobster__loop__pb2.StatusRequest.FromString,
            response_serializer=lobster__loop__pb2.StatusResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=lobster__loop__pb2.HealthRequest.FromString,
            response_serializer=lobster__loop__pb2.HealthResponse.SerializeToString,
        ),
        "Subscribe": grpc.unary_stream_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=lobster__loop__pb2.SubscribeRequest.FromString,
            response_serializer=lobster__loop__pb2.Event.SerializeToString,
        ),
        "InterClaw": grpc.unary_unary_rpc_method_handler(
            servicer.InterClaw,
            request_deserializer=lobster__loop__pb2.InterClawRequest.FromString,
            response_serializer=lobster__loop__pb2.InterClawResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "lobster.party.v1.LobsterLoop", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("lobster.party.v1.LobsterLoop", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class LobsterLoop:
    """=============================================================================
    Service Definition: LobsterLoop
    =============================================================================

    LobsterLoop is the primary gRPC service exposed by each Claw runtime.
    The Clawplexer uses this service to:

    1. Submit work turns (Turn RPC)
    2. Query Claw status (Status RPC)
    3. Check Claw health (Health RPC)
    4. Subscribe to state change events (Subscribe RPC - server streaming)
    5. Send InterClaw requests to other Claws (InterClaw RPC)

    Communication Pattern
    --------------------

    The Clawplexer is the client; the Claw runtime is the server.
    This allows Claws to run without egress network access (common in K8s).

    Claw Runtime Pod Network
    ------------------------

    Claw Pods are addressed via their ClusterIP Service:

    claw-<claw_id>.lobster-party-runtime.svc:50051

    The Clawplexer maintains an endpoint cache (from K8s EndpointSlices) and
    routes gRPC calls to ready Pod endpoints only.

    Error Handling Convention
    -------------------------

    All RPCs return gRPC status codes:
    - OK (0):              Success
    - INVALID_ARGUMENT:     Malformed request (e.g., bad event_id)
    - NOT_FOUND:           Claw does not exist or is not routable
    - FAILED_PRECONDITION: Claw is not in a state that accepts work (e.g., paused)
    - UNAVAILABLE:         Claw is temporarily unreachable or overloaded
    - INTERNAL:            Unexpected error in Claw runtime
    - PERMISSION_DENIED:   InterClaw request denied by ACL
    - RESOURCE_EXHAUSTED:  InterClaw request pending permission

    """

    @staticmethod
    def Turn(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/lobster.party.v1.LobsterLoop/Turn",
            lobster__loop__pb2.TurnRequest.SerializeToString,
            lobster__loop__pb2.TurnStreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Status(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.LobsterLoop/Status",
            lobster__loop__pb2.StatusRequest.SerializeToString,
            lobster__loop__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.LobsterLoop/Health",
            lobster__loop__pb2.HealthRequest.SerializeToString,
            lobster__loop__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Subscribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/lobster.party.v1.LobsterLoop/Subscribe",
            lobster__loop__pb2.SubscribeRequest.SerializeToString,
            lobster__loop__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def InterClaw(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lobster.party.v1.LobsterLoop/InterClaw",
            lobster__loop__pb2.InterClawRequest.SerializeToString,
            lobster__loop__pb2.InterClawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
